namespace: argocd
resources:
  - namespace.yaml
  - argocd.yaml

patches:
  - path: kustomize-enable-helm.patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      version: v1
      kind: Service
      name: argocd-server
