resources:
  - namespace.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.17.0
    releaseName: cilium
    namespace: cilium-system
    includeCRDs: true
    valuesFile: values.yaml
